groups:
  - name: aoe_alerts
    rules:
      - alert: TargetAppDown
        expr: up{job="aoe-target-app"} == 0
        for: 10s
        labels:
          severity: 'critical'
        annotations:
          summary: 'Aplicação alvo está offline'
          description: 'O serviço aoe-target-app não está respondendo ao Prometheus.'

      - alert: Port9090Blocked
        expr: aoe_port_in_use{job="aoe-service-manager"} == 1
        for: 5s
        labels:
          severity: 'warning'
        annotations:
          summary: 'Porta 9090 está bloqueada'
          description: 'A porta 9090 parece estar bloqueada por outro processo, impedindo a inicialização do serviço.'

      - alert: HighCpuLoad
        expr: aoe_cpu_load_high{job="aoe-service-manager"} == 1
        for: 15s
        labels:
          severity: 'critical'
        annotations:
          summary: 'Carga de CPU Alta Detectada'
          description: 'O sistema detectou uma carga de CPU anormalmente alta, potencialmente causada por um processo descontrolado.'
